version: '3'
services:
  adguard-home:
    image: mort3m/test:latest
    container_name: adguard-home
    restart: always
    network_mode: bridge
    volumes:
      - adguard-home-data:/data
    ports:
      - "53:53"
      - "1337:3000"
volumes:
  adguard-home-data:
    driver: local